### PR TITLE
Implement a fully-Dockerized setup.

### PR DESCRIPTION
**Pull request by freerobby**
This is an alternate implementation of #5, with the following differences:

* All systems are provided in a single container.
* Dashboards are automatically generated via curl requests to the Grafana API.
* No dependency on docker-compose.

I'm not sure which approach is preferable for the project. I think @dailow's is better-suited to long-term installations (due to the customization of the data directory and the separation of concerns among containers), whereas mine excels at getting a working version up very quickly.

### CODE REVIEW

**Comment by lephisto** [comment]
Thanks for PR, I will test it, will last some days for sure.

**Comment by lephisto** [comment]
please pr again... sry for trouble..

**Comment by freerobby** [comment]
@lephisto No worries, but I'm not sure what the intention is here. Do you want me to just make a PR that reverts your revert?

**Comment by freerobby** [comment]
I will go ahead and do that, but feel free to close it out if that's not what you intended.

**Comment by lephisto** [comment]
I made a mistake prior merging your PR; so it was easier for me doing a reset --hard. thanks for contributing, will merge tomorrow.

**Pull request merged**
